// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwaiqnhqjyazxgqvqrsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3YWlxbmhxanlhenhncXZxcnN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODY2MjksImV4cCI6MjA1ODQ2MjYyOX0.mryF-vHcjJFRc5YU_qJV65MbtE8Xo70GBVzM2IJNrHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);