// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwaiqnhqjyazxgqvqrsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3YWlxbmhxanlhenhncXZxcnN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDIzNDQsImV4cCI6MjA2NDUxODM0NH0.kSTisA_IOrrMLuI2Inyy0LqmUUcCu_Pa1sUbiDZagXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);